import React from 'react';
import { FileText, BookTemplate, Users, TrendingUp, Clock, User, MessageCircle, RefreshCw, Star } from 'lucide-react';
import { Button } from './ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from './ui/card';
import { Badge } from './ui/badge';
import { Avatar, AvatarFallback, AvatarImage } from './ui/avatar';
import { Separator } from './ui/separator';

interface DashboardProps {
  onNavigate: (page: string, id?: string) => void;
}

const recentActivity = [
  {
    id: 1,
    type: 'document',
    title: 'API Service Documentation',
    action: 'generated by Alice',
    time: '2 hours ago',
    status: 'completed',
    icon: FileText
  },
  {
    id: 2,
    type: 'template',
    title: 'AWS Infrastructure Template',
    action: 'updated by Bob',
    time: '4 hours ago',
    status: 'updated',
    icon: BookTemplate
  },
  {
    id: 3,
    type: 'comment',
    title: 'User Management Service Docs',
    action: 'commented by Carol',
    time: '6 hours ago',
    status: 'new',
    icon: MessageCircle
  },
  {
    id: 4,
    type: 'generation',
    title: 'K8s Deployment Guide',
    action: 'auto-generated',
    time: '8 hours ago',
    status: 'scheduled',
    icon: RefreshCw
  }
];

const teamMembers = [
  { name: 'Alice Johnson', avatar: 'AJ', role: 'Team Lead', active: true },
  { name: 'Bob Smith', avatar: 'BS', role: 'DevOps Engineer', active: true },
  { name: 'Carol Davis', avatar: 'CD', role: 'Tech Writer', active: false },
  { name: 'David Lee', avatar: 'DL', role: 'Developer', active: true },
];

const communityHighlights = [
  {
    title: 'K8s Deployment Doc Template',
    author: 'JaneDoe',
    uses: 120,
    rating: 4.8,
    trending: true
  },
  {
    title: 'API Documentation Generator',
    author: 'TechGuru',
    uses: 95,
    rating: 4.6,
    trending: false
  }
];

export function Dashboard({ onNavigate }: DashboardProps) {
  return (
    <div className="p-6 space-y-6">
      {/* Welcome Header */}
      <div className="flex items-center justify-between">
        <div className="space-y-2">
          <h1 className="text-2xl font-semibold">Hello, John! 👋</h1>
          <p className="text-muted-foreground">Acme Corp – Engineering Team</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={() => onNavigate('generate')}>
            <FileText className="h-4 w-4 mr-2" />
            Generate Docs
          </Button>
          <Button variant="outline" onClick={() => onNavigate('templates')}>
            <BookTemplate className="h-4 w-4 mr-2" />
            Templates
          </Button>
          <Button onClick={() => onNavigate('repository')}>
            <Star className="h-4 w-4 mr-2" />
            Repository
          </Button>
        </div>
      </div>

      {/* Quick Actions */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <Card className="cursor-pointer hover:shadow-md transition-shadow" onClick={() => onNavigate('generate')}>
          <CardHeader className="pb-3">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-primary/10 rounded-lg">
                <FileText className="h-6 w-6 text-primary" />
              </div>
              <div>
                <CardTitle className="text-lg">Generate Documentation</CardTitle>
                <CardDescription>Create new docs from your sources</CardDescription>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <Button className="w-full">Get Started</Button>
          </CardContent>
        </Card>

        <Card className="cursor-pointer hover:shadow-md transition-shadow" onClick={() => onNavigate('templates')}>
          <CardHeader className="pb-3">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-secondary/50 rounded-lg">
                <BookTemplate className="h-6 w-6 text-secondary-foreground" />
              </div>
              <div>
                <CardTitle className="text-lg">Create New Template</CardTitle>
                <CardDescription>Build custom documentation templates</CardDescription>
              </div>
            </div>
          </CardHeader>
          <CardContent>
            <Button variant="secondary" className="w-full">Start Building</Button>
          </CardContent>
        </Card>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Recent Activity */}
        <Card className="lg:col-span-2">
          <CardHeader className="pb-4">
            <div className="flex items-center justify-between">
              <CardTitle className="flex items-center gap-2">
                <Clock className="h-5 w-5" />
                Recent Activity
              </CardTitle>
              <Button variant="ghost" size="sm" onClick={() => onNavigate('repository')}>
                View All
              </Button>
            </div>
          </CardHeader>
          <CardContent className="space-y-4">
            {recentActivity.map((item, index) => {
              const Icon = item.icon;
              return (
                <div key={item.id}>
                  <div className="flex items-start gap-3">
                    <div className="p-1.5 bg-muted rounded">
                      <Icon className="h-4 w-4" />
                    </div>
                    <div className="flex-1 space-y-1">
                      <div className="flex items-center gap-2">
                        <span className="font-medium">{item.title}</span>
                        <Badge variant={
                          item.status === 'completed' ? 'default' :
                          item.status === 'updated' ? 'secondary' :
                          item.status === 'new' ? 'destructive' : 'outline'
                        } className="text-xs">
                          {item.status}
                        </Badge>
                      </div>
                      <p className="text-sm text-muted-foreground">
                        {item.action} • {item.time}
                      </p>
                    </div>
                  </div>
                  {index < recentActivity.length - 1 && <Separator className="mt-4" />}
                </div>
              );
            })}
          </CardContent>
        </Card>

        <div className="space-y-6">
          {/* Team Overview */}
          <Card>
            <CardHeader className="pb-4">
              <CardTitle className="flex items-center gap-2">
                <Users className="h-5 w-5" />
                Team Overview
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-3">
                {teamMembers.slice(0, 3).map((member, index) => (
                  <div key={index} className="flex items-center gap-3">
                    <Avatar className="h-8 w-8">
                      <AvatarFallback>{member.avatar}</AvatarFallback>
                    </Avatar>
                    <div className="flex-1">
                      <p className="text-sm font-medium">{member.name}</p>
                      <p className="text-xs text-muted-foreground">{member.role}</p>
                    </div>
                    <div className={`h-2 w-2 rounded-full ${member.active ? 'bg-green-500' : 'bg-gray-300'}`} />
                  </div>
                ))}
              </div>
              {teamMembers.length > 3 && (
                <Button variant="ghost" size="sm" className="w-full">
                  +{teamMembers.length - 3} more members
                </Button>
              )}
            </CardContent>
          </Card>

          {/* Community Highlights */}
          <Card>
            <CardHeader className="pb-4">
              <CardTitle className="flex items-center gap-2">
                <TrendingUp className="h-5 w-5" />
                Community Spotlight
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              {communityHighlights.map((template, index) => (
                <div key={index} className="space-y-2">
                  <div className="flex items-start justify-between">
                    <div className="space-y-1">
                      <div className="flex items-center gap-2">
                        <p className="text-sm font-medium">{template.title}</p>
                        {template.trending && <Badge variant="secondary" className="text-xs">🔥 Trending</Badge>}
                      </div>
                      <p className="text-xs text-muted-foreground">by {template.author}</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-4 text-xs text-muted-foreground">
                    <span className="flex items-center gap-1">
                      <Star className="h-3 w-3 fill-current" />
                      {template.rating}
                    </span>
                    <span>{template.uses} uses</span>
                  </div>
                  {index < communityHighlights.length - 1 && <Separator className="mt-4" />}
                </div>
              ))}
              <Button variant="ghost" size="sm" className="w-full" onClick={() => onNavigate('community')}>
                Explore Community
              </Button>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}